defmodule FourLucha.Resource.Game do
  @moduledoc false
  defstruct(
    aliases: nil,
    api_detail_url: nil,
    characters: nil,
    concepts: nil,
    date_added: nil,
    date_last_updated: nil,
    deck: nil,
    description: nil,
    developers: nil,
    expected_release_day: nil,
    expected_release_quarter: nil,
    expected_release_year: nil,
    expected_release_month: nil,
    first_appearance_characters: nil,
    first_appearance_concepts: nil,
    first_appearance_locations: nil,
    first_appearance_objects: nil,
    first_appearance_people: nil,
    franchises: nil,
    genres: nil,
    guid: nil,
    id: nil,
    image: nil,
    images: nil,
    image_tags: nil,
    killed_characters: nil,
    locations: nil,
    name: nil,
    number_of_user_reviews: nil,
    objects: nil,
    original_game_rating: nil,
    original_release_date: nil,
    people: nil,
    platforms: nil,
    publishers: nil,
    releases: nil,
    dlcs: nil,
    reviews: nil,
    similar_games: nil,
    site_detail_url: nil,
    themes: nil,
    videos: nil
  )
end
